sonar.projectKey=loglens
sonar.organization=loglens-org
sonar.projectName=LogLens
sonar.sources=LogLens.Core,LogLens.Api,../loglens-web/src
sonar.tests=LogLens.Core.Tests,LogLens.Api.Tests
sonar.cs.opencover.reportsPaths=coverage/**/coverage.opencover.xml
sonar.javascript.lcov.reportPaths=loglens-web/coverage/lcov.info
sonar.exclusions=**/Migrations/**,**/node_modules/**,**/*.min.js
