// <auto-generated />
using System;
using LogSage.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogSage.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417100000_RemoveFeedbackNote")]
    partial class RemoveFeedbackNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogSage.Api.Data.Entities.ParseSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DebugCount")
                        .HasColumnType("integer");

                    b.Property<string>("DetectedFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FeedbackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FeedbackScore")
                        .HasColumnType("integer");

                    b.Property<int>("InfoCount")
                        .HasColumnType("integer");

                    b.Property<int>("InputLineCount")
                        .HasColumnType("integer");

                    b.Property<string>("InputSample")
                        .HasColumnType("text");

                    b.Property<int>("InputSizeBytes")
                        .HasColumnType("integer");

                    b.Property<int>("ParseErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("ParseErrorSamples")
                        .HasColumnType("text");

                    b.Property<bool>("ParseSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalEntries")
                        .HasColumnType("integer");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken");

                    b.ToTable("ParseSessions");
                });

            modelBuilder.Entity("LogSage.Api.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DebugCount")
                        .HasColumnType("integer");

                    b.Property<string>("DetectedFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<int>("InfoCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("LogSage.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LogSage.Api.Data.Entities.ErrorGroup", b =>
                {
                    b.HasOne("LogSage.Api.Data.Entities.Session", null)
                        .WithMany("ErrorGroups")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogSage.Api.Data.Entities.Session", b =>
                {
                    b.HasOne("LogSage.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogSage.Api.Data.Entities.Session", b =>
                {
                    b.Navigation("ErrorGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
