sonar.projectKey=LogSage
sonar.organization=LogSage-org
sonar.projectName=LogSage
sonar.sources=LogSage.Core,LogSage.Api,../logsage-web/src
sonar.tests=LogSage.Core.Tests,LogSage.Api.Tests
sonar.cs.opencover.reportsPaths=coverage/**/coverage.opencover.xml
sonar.javascript.lcov.reportPaths=logsage-web/coverage/lcov.info
sonar.exclusions=**/Migrations/**,**/node_modules/**,**/*.min.js
